name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/main.yml
    with:
      buildFlags: officialBuild
      
  release-linux:
    name: Release linuxBuild.zip
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        path: build
        name: linuxBuild
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r build.zip build
    - name: Upload linuxBuild to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: Linux64.zip
        overwrite: false

  release-mac:
    name: Release macBuild.zip
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Mac artifact
      uses: actions/download-artifact@v3
      with:
        path: build
        name: macBuild
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r build.zip build
    - name: Upload macBuild to release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: build.zip
        asset_name: Mac64.zip
        overwrite: false
